#!/bin/bash

# Unified runner for the Toit Stress Tool
# Automatically translates parameters.cfg into a Toit config file and executes.

TARGET="jag" # Default target
CONTAINERS=""

# Check if first parameter is a number
if [[ "$1" =~ ^[0-9]+$ ]]; then
    CONTAINERS=$1
    shift
fi

# Parse CLI arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --jag|-j) TARGET="jag"; shift ;;
        --toit|-t) TARGET="toit"; shift ;;
        --help|-h) 
            echo "Usage: ./stress_tool.sh [task_count] [options]"
            echo "Options:"
            echo "  -j, --jag    Run on an ESP32 device using Jaguar (default)"
            echo "  -t, --toit   Run locally using the Toit VM"
            echo "  -h, --help   Show this help message"
            echo ""
            echo "Example: ./stress_tool.sh 15 -t"
            exit 0
            ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
done

# Ensure parameters.cfg exists
if [ ! -f "parameters.cfg" ]; then
    echo "Error: parameters.cfg not found!"
    echo "Creating a default parameters.cfg..."
    cat > parameters.cfg << 'EOF'
DEFAULT_TASKS=5
DEFAULT_INTENSITY=0.65
DEFAULT_DURATION_SECONDS=30
EOF
fi

echo "Translating parameters.cfg..."

# Generate config.toit on the fly
echo "// Auto-generated by stress_tool.sh from parameters.cfg" > config.toit
while IFS='=' read -r key value; do
    # Skip empty lines or comments
    if [[ -z "$key" || "$key" == \#* ]]; then continue; fi
    
    # Trim whitespace
    key=$(echo "$key" | xargs)
    value=$(echo "$value" | xargs)
    
    if [[ -n "$key" && -n "$value" ]]; then
        if [[ "$key" == "DEFAULT_TASKS" && -n "$CONTAINERS" ]]; then
            value="$CONTAINERS"
        fi
        echo "${key} ::= ${value}" >> config.toit
    fi
done < parameters.cfg

# Execute based on target
if [ "$TARGET" == "jag" ]; then
    echo "Running on ESP32 via Jaguar..."
    jag run stress_tool.toit
else
    echo "Running locally via Toit VM..."
    toit run stress_tool.toit
fi

# Cleanup
rm config.toit
