#!/bin/bash

# Unified runner for the Toit Stress Tool
# Automatically translates parameters.cfg into a Toit config file and executes.

TARGET="jag" # Default target
CONTAINERS=""
EXTRA_ARGS=""

# Handle cleanup of child processes (like the Toit VM) on exit
cleanup() {
    # Kill any process that is running the stress tool.
    # This ensures grandchildren (Toit VM) are killed even if the wrapper is intermediate.
    pkill -9 -f "stress_tool.toit" 2>/dev/null
    exit 1
}
trap cleanup SIGINT SIGTERM

# Parse CLI arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --jag|-j) TARGET="jag"; shift ;;
        --toit|-t) TARGET="toit"; shift ;;
        --silent|-s) SILENT=true; shift ;;
        --help|-h) 
            echo "Usage: ./stress_tool.sh [options] [-- [toit_args]]"
            echo "Options:"
            echo "  -j, --jag        Run on an ESP32 device using Jaguar (default)"
            echo "  -t, --toit       Run locally using the Toit VM"
            echo "  -s, --silent     Suppress translation and execution info messages"
            echo "  -h, --help       Show this help message"
            echo ""
            echo "Example: ./stress_tool.sh -t --silent -- --print"
            exit 0
            ;;
        --) shift; EXTRA_ARGS="$EXTRA_ARGS $@"; break ;;
        *) EXTRA_ARGS="$EXTRA_ARGS $1"; shift ;;
    esac
done

# Ensure parameters.cfg exists
if [ ! -f "parameters.cfg" ]; then
    echo "Error: parameters.cfg not found!"
    echo "Creating a default parameters.cfg..."
    cat > parameters.cfg << 'EOF'
DEFAULT_TASKS=5
DEFAULT_INTENSITY=0.65
DURATION=30
EOF
fi

if [ "$SILENT" != true ]; then
    echo "Translating parameters.cfg..."
fi

# Generate config.toit on the fly atomically to avoid race conditions
TMP_FILE="config_$$.toit"
echo "// Auto-generated by stress_tool.sh from parameters.cfg" > "$TMP_FILE"
while IFS='=' read -r key value; do
    # Skip empty lines or comments
    if [[ -z "$key" || "$key" == \#* ]]; then continue; fi
    
    # Trim whitespace
    key=$(echo "$key" | xargs)
    value=$(echo "$value" | xargs)
    
    if [[ -n "$key" && -n "$value" ]]; then
        echo "${key} ::= ${value}" >> "$TMP_FILE"
    fi
done < parameters.cfg

mv "$TMP_FILE" config.toit

# Execute based on target
if [ "$TARGET" == "jag" ]; then
    if [ "$SILENT" != true ]; then echo "Running on ESP32 via Jaguar..."; fi
    jag run stress_tool.toit
else
    if [ "$SILENT" != true ]; then echo "Running locally via Toit VM..."; fi
    toit run stress_tool.toit -- $EXTRA_ARGS
fi

# We intentionally do NOT delete config.toit here to avoid breaking concurrent toit run processes.
